@startuml

header Gremlin AUTH workflow 
title How users request access to Gremlin
autonumber
actor Requester
actor COEApprover 
actor OktaAdmin
actor ADAdmin

database ActiveDirectory
hnote over ActiveDirectory: UserName
hnote over ActiveDirectory: ADGroup

group Request access
    Requester -> COEApprover: Request Access
    group Deny Request
        COEApprover->x Requester: Deny
    end
    group Approve Request
        COEApprover -> Requester: Approved
        COEApprover -> ServiceTicket
        note right: Submit ticket to AD TEAM
        ServiceTicket -> ADAdmin
        note right: Add user to AD Group
        ADAdmin -> ServiceTicket: update ServiceTicket
        ServiceTicket -> OktaAdmin: update Okta as needed
        OktaAdmin -> ServiceTicket: update ServiceTicket
        ServiceTicket -> ServiceTicket: Notify COEApprover
    end
    ServiceTicket -> COEApprover
    COEApprover -> Requester: Notify Requester 

end

boundary Gremlin
database GremlinAUTH
hnote over GremlinAUTH: UserName
hnote over GremlinAUTH: TeamID

@enduml