@startuml

header TechOps ADAXES
title User ADD to AD Group
autonumber
actor Developer
database LDAPGroup
actor LDAPOwner

boundary VaultNamespace
Developer -> Vault: Login to Vault

note right
    access to Vault is 
    provided via TechOps 
    AD Group
end note
alt Login denied
    Vault -> Developer: DENIED
    Developer -> LDAPGroup: TechOps AD
    note right
        ADAXES PRD Group
        Request add to LDAP 
        Group Owner
    end note
    LDAPGroup -> LDAPOwner: Add Developer to Group
    note right
        AD Group Owner
        adds user to
        group
    end note
    LDAPOwner -> Developer: Notify Developer

else Login allowed
    Vault -> Developer: ALLOWED
    Developer -> VaultNamespace: Access Namespace
end


group Vault Namespace
alt Namespace exists
    LDAPGroup -> VaultNamespace: Access provide to Namespace
    VaultNamespace -> Developer: Request complete

else Namespace does not exists
    LDAPGroup -> Vault: Add Namespace to Vault
    Vault -> VaultNamespace: Add TechOps LDAP Group
    VaultNamespace -> Developer: Request complete
end

@enduml