@startuml

header TechOps ADAXES
title User ADD to AD Group
autonumber
actor Developer
database LDAPGroup
actor LDAPOwner
actor Vault
hnote over Vault: PKI 
hnote over Vault: KVP
hnote over Vault: Transit
hnote over Vault: TLS

boundary VaultNamespace
Developer -> Vault: Login to Vault

note right
    access to Vauly is 
    provided via TechOps 
    AD Group
end note
alt Login denied
    Vault -> Developer: DENIED
    Developer -> LDAPGroup: TechOps AD
    LDAPGroup -> LDAPOwner: Add Developer to Group
    LDAPOwner -> Developer: Update Developer
end

alt Login allowed
    Vault -> Developer: ALLOWED
    Developer -> VaultNamespace: Access Namespace
end


group Vault Namespace
alt Namespace exists
    LDAPGroup -> VaultNamespace: Access provide to Namespace
    VaultNamespace -> Developer: Request complete

else Namespace does not exists
    LDAPGroup -> Vault: Add Namespace to Vault
    Vault -> VaultNamespace: Add TechOps LDAP Group
    VaultNamespace -> Developer: Request complete
end



@enduml